leftnav:
- identifier: d9eb8c7e-b9ac-42db-83d1-5e36b8189f5d
  name: Section 1 Menu Title
  url: /pages/section-1
  weight: 10
- identifier: 018d07b5-0f37-493f-8025-53a3ee837168
  name: Section 2 Menu Title
  url: /pages/assignments
  weight: 20
- identifier: 7e1d1926-96b4-4f0c-b4b6-2f34ab7562f6
  name: Shortcode Demos
  url: /pages/shortcode-demos
  weight: 30
- identifier: 7b3ae5c4-3b27-4806-b0c5-f012f16fa245
  name: Subscripts and Superscripts
  url: /pages/subscripts-and-superscripts
  weight: 40
- identifier: d1f35266-366e-45f1-bfc2-bcd46eb6c4a4
  name: Subsection 1a Menu Title
  parent: d9eb8c7e-b9ac-42db-83d1-5e36b8189f5d
  url: /pages/subsection-1a
  weight: 10
- identifier: 874d2ec0-06db-40da-b376-4f6579590d20
  name: Subsection 1b Menu Title
  parent: d9eb8c7e-b9ac-42db-83d1-5e36b8189f5d
  url: /pages/subsection-1b
  weight: 20
- identifier: a9916d12-f128-bdd2-a11b-02e75f786ba1
  name: Video Series Overview
  url: /pages/video-series-overview/
  weight: 50
- identifier: a7716d12-f128-bdd2-a11b-02e75f786ba1
  name: Multiple Videos Series Overview
  url: /pages/multiple-videos-series-overview/
  weight: 60
- identifier: 79392061-a205-4e93-83f2-276dbc9668e6
  name: Resource List
  url: /lists/a-resource-list
  weight: 80
- identifier: external--1632447086-1696840247084
  name: An External Link
  url: https://www.google.com
  weight: 90
- identifier: external--1632447086-1696840247085
  name: An External OCW Link
  url: https://ocw.mit.edu
  weight: 100
  params:
    includeLicenseWarning: false
