name: CI
on: [push]

jobs:
  javascript-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint
        run: yarn lint

      - name: Tests
        run: yarn test

      - name: Code formatting
        run: yarn fmt:check

      - name: typechecking
        run: yarn typecheck

  test-e2e:
    env:
      OCW_STUDIO_BASE_URL: ${{ secrets.OCW_STUDIO_BASE_URL }}
      SEARCH_API_URL: ${{ secrets.SEARCH_API_URL }}
      STATIC_API_BASE_URL: ${{ secrets.STATIC_API_BASE_URL }}
      RESOURCE_BASE_URL: ${{ secrets.RESOURCE_BASE_URL }}
      COURSE_HUGO_CONFIG_PATH: "$GITHUB_WORKSPACE/ocw-hugo-projects/ocw-course-v2/config.yaml"
      WWW_HUGO_CONFIG_PATH: "$GITHUB_WORKSPACE/ocw-hugo-projects/ocw-www/config.yaml"
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - uses: actions/checkout@v3
      with:
        repository: "mitodl/ocw-hugo-projects"
        ref: "main"
        path: "ocw-hugo-projects"
    - name: Install dependencies
      run: yarn
    - name: Run e2e jest tests
      run: yarn test:e2e:jest
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Build Webpack
      run: yarn build:webpack:dev
    - name: Run Playwright tests
      run: yarn test:e2e video.spec.ts --repeat-each 100
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30