name: CI
on: [push]

jobs:
  javascript-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint
        run: yarn lint

      - name: Tests
        run: yarn test

      - name: Code formatting
        run: yarn fmt:check

      - name: typechecking
        run: yarn typecheck
